<%@ Page Title="" Language="C#" MasterPageFile="~/ManageSiteViewReport.Master" AutoEventWireup="true" CodeBehind="PDtoExcel.aspx.cs" Inherits="HVP.Survey.PDtoExcel" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <asp:HiddenField ID="hfsiteid" runat="server" />
    <asp:HiddenField ID="hfSchdId" runat="server" />
     <div class="userlist">
   <div> <h1 class="users">PD Export to Excel</h1></div> 
         <div><h2 class="Sitename">Sitename:
            <asp:Label ID="lblSitename" runat="server"></asp:Label></h2>
            <h4 class="Sitename">Program ID: <asp:Label ID="lblProgramId" runat="server"></asp:Label></h4>
        </div>   
     <%--<h4>SELECT SITE :<asp:DropDownList ID="ddlSites" runat="server" DataSourceID="SqlDataSource3" DataTextField="Sites" DataValueField="Schd_ID" AppendDataBoundItems="True"></asp:DropDownList>
        <asp:Button ID="btnView" runat="server" Text="View" OnClick="btnView_Click" />
          </h4>
         <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:ISBEPI_DEV %>" SelectCommand="SELECT ST.Sites, SCHD.Schd_ID FROM Sites AS ST RIGHT JOIN [ISBEPI_DEV].[dbo].[Scheduling] SCHD ON SCHD.SiteID = ST.SiteID RIGHT JOIN [ISBEPI_DEV].[dbo].[Program_Director_Survey] PD ON PD.Schd_ID = SCHD.Schd_ID  WHERE SCHD.Schd_ID != '23' AND SCHD.Schd_ID != '25' GROUP BY ST.Sites, SCHD.Schd_ID"></asp:SqlDataSource>--%>
   
     <div style="width: 100%; height: 400px; overflow: scroll">
         <asp:DataGrid ID="DataGrid1" runat="server">
         </asp:DataGrid>
         <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ISBEPI_DEV %>" SelectCommand="SELECT [PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q1]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q2]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q3]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q4]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q4_Other],
     CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_Yes_or_no]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_Yes_or_no
      ,CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_1]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_1
      ,CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_2]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_2
      ,CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_3]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_3
      ,CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_4]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_4
      ,CAST([PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_5]  AS INT) AS PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_5
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q5_5_OTher]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q6]
      ,[PD_DEMOGRAPHICS_BASICPROGRAMINFORMATION_Q6_Other]
      ,[PD_FAMILYINFORMATION_Q7]
      ,[PD_FAMILYINFORMATION_Q8_1]
      ,[PD_FAMILYINFORMATION_Q8_2]
      ,[PD_FAMILYINFORMATION_Q8_3]
      ,[PD_FAMILYINFORMATION_Q8_4]
      ,[PD_FAMILYINFORMATION_Q8_5]
      ,[PD_FAMILYINFORMATION_Q8_6]
      ,[PD_FAMILYINFORMATION_Q8_7]
      ,[PD_FAMILYINFORMATION_Q8_Total]
      ,[PD_FAMILYINFORMATION_Q9_1]
      ,[PD_FAMILYINFORMATION_Q9_2]
      ,[PD_FAMILYINFORMATION_Q9_3]
      ,[PD_FAMILYINFORMATION_Q9_4]
      ,[PD_FAMILYINFORMATION_Q9_5]
      ,[PD_FAMILYINFORMATION_Q9_6]
      ,[PD_FAMILYINFORMATION_Q9_Total]
      ,[PD_FAMILYINFORMATION_Q10_1]
      ,[PD_FAMILYINFORMATION_Q10_2]
      ,[PD_FAMILYINFORMATION_Q10_3]
      ,[PD_FAMILYINFORMATION_Q10_4]
      ,[PD_FAMILYINFORMATION_Q10_5]
      ,[PD_FAMILYINFORMATION_Q10_Total]
      ,CAST([PD_FAMILYINFORMATION_Q11_1]  AS INT) AS PD_FAMILYINFORMATION_Q11_1
      ,CAST([PD_FAMILYINFORMATION_Q11_2]  AS INT) AS PD_FAMILYINFORMATION_Q11_2
      ,CAST([PD_FAMILYINFORMATION_Q11_3]  AS INT) AS PD_FAMILYINFORMATION_Q11_3
      ,CAST([PD_FAMILYINFORMATION_Q11_4]  AS INT) AS PD_FAMILYINFORMATION_Q11_4
      ,CAST([PD_FAMILYINFORMATION_Q11_5]  AS INT) AS PD_FAMILYINFORMATION_Q11_5
      ,CAST([PD_FAMILYINFORMATION_Q11_6]  AS INT) AS PD_FAMILYINFORMATION_Q11_6
      ,CAST([PD_FAMILYINFORMATION_Q11_7]  AS INT) AS PD_FAMILYINFORMATION_Q11_7
      ,[PD_FAMILYINFORMATION_Q11_6_other]    
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_1]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_2]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_3]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_4]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_5]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_6]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_7]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_8]
      ,[PD_INITIALTRAINING_Q19_1_CHILDDEVELOPMENT_9]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_1]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_2]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_3]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_4]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_5]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_6]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_7]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_8]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_9]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_10]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_11]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_12]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_13]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_14]
      ,[PD_INITIALTRAINING_Q19_2_CHILDHEALTHANDSAFETY_15]
      ,[PD_INITIALTRAINING_Q19_3_PARENTCHILDRELATINONSHIPS_1]
      ,[PD_INITIALTRAINING_Q19_3_PARENTCHILDRELATINONSHIPS_2]
      ,[PD_INITIALTRAINING_Q19_3_PARENTCHILDRELATINONSHIPS_3]
      ,[PD_INITIALTRAINING_Q19_3_PARENTCHILDRELATINONSHIPS_4]
      ,[PD_INITIALTRAINING_Q19_3_PARENTCHILDRELATINONSHIPS_5]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_1]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_2]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_3]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_4]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_5]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_6]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_7]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_8]
      ,[PD_ONGOINGTRAINING_Q20_1_CHILDDEVELOPMENT_9]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_1]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_2]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_3]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_4]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_5]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_6]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_7]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_8]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_9]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_10]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_11]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_12]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_13]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_14]
      ,[PD_ONGOINGTRAINING_Q20_2_CHILDHEALTHANDSAFETY_15]
      ,[PD_ONGOINGTRAINING_Q20_3_PARENTCHILDRELATINONSHIPS_1]
      ,[PD_ONGOINGTRAINING_Q20_3_PARENTCHILDRELATINONSHIPS_2]
      ,[PD_ONGOINGTRAINING_Q20_3_PARENTCHILDRELATINONSHIPS_3]
      ,[PD_ONGOINGTRAINING_Q20_3_PARENTCHILDRELATINONSHIPS_4]
      ,[PD_ONGOINGTRAINING_Q20_3_PARENTCHILDRELATINONSHIPS_5]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_1]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_2]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_3]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_4]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_5]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_6]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_7]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_8]
      ,[PD_PROGRAMMATERIAL_Q21_1_CHILDDEVELOPMENT_9]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_1]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_2]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_3]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_4]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_5]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_6]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_7]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_8]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_9]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_10]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_11]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_12]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_13]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_14]
      ,[PD_PROGRAMMATERIAL_Q21_2_CHILDHEALTHANDSAFETY_15]
      ,[PD_PROGRAMMATERIAL_Q21_3_PARENTCHILDRELATINONSHIPS_1]
      ,[PD_PROGRAMMATERIAL_Q21_3_PARENTCHILDRELATINONSHIPS_2]
      ,[PD_PROGRAMMATERIAL_Q21_3_PARENTCHILDRELATINONSHIPS_3]
      ,[PD_PROGRAMMATERIAL_Q21_3_PARENTCHILDRELATINONSHIPS_4]
      ,[PD_PROGRAMMATERIAL_Q21_3_PARENTCHILDRELATINONSHIPS_5]
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_22]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_22
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_1]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_1
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_2]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_2
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_3]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_3
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_4]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_4
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_5]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_5
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_6]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_6
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_7]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_7
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_8]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_8
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_9]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_9
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_10]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_10
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_11]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_11
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_12]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_12
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_13]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_13
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_14]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_14
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_15]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_15
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_16]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_16
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_17]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_17
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_18]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_18
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_19]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_19
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_20]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_20
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_21]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_21
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_22]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_22
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_23]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_23
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_24]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_24
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_25]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_25
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_26]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_26
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_27]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_27
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_28]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_28
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_29]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_29
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q23_30]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q23_30
      ,[PD_WRITTENPOLICIESANDPROCEDURES_Q24]
      ,[PD_WRITTENPOLICIESANDPROCEDURES_Q25]
      ,CAST([PD_WRITTENPOLICIESANDPROCEDURES_Q26]  AS INT) AS PD_WRITTENPOLICIESANDPROCEDURES_Q26
      ,[PD_WRITTENPOLICIESANDPROCEDURES_Q26_Describe]
      ,CAST([PD_DataCollectionProcess_Q27_1]  AS INT) AS PD_DataCollectionProcess_Q27_1
      ,CAST([PD_DataCollectionProcess_Q27_2]  AS INT) AS PD_DataCollectionProcess_Q27_2
      ,CAST([PD_DataCollectionProcess_Q27_3]  AS INT) AS PD_DataCollectionProcess_Q27_3
      ,CAST([PD_DataCollectionProcess_Q27_4]  AS INT) AS PD_DataCollectionProcess_Q27_4
      ,[PD_DataCollectionProcess_Q27_other]
      ,CAST([PD_DataCollectionProcess_Q28_1]  AS INT) AS PD_DataCollectionProcess_Q28_1
      ,CAST([PD_DataCollectionProcess_Q28_2]  AS INT) AS PD_DataCollectionProcess_Q28_2
      ,CAST([PD_DataCollectionProcess_Q29_1]  AS INT) AS PD_DataCollectionProcess_Q29_1
      ,CAST([PD_DataCollectionProcess_Q29_2]  AS INT) AS PD_DataCollectionProcess_Q29_2
      ,CAST([PD_DataCollectionProcess_Q29_3]  AS INT) AS PD_DataCollectionProcess_Q29_3
      ,CAST([PD_DataCollectionProcess_Q30_1]  AS INT) AS PD_DataCollectionProcess_Q30_1
      ,CAST([PD_DataCollectionProcess_Q30_2]  AS INT) AS PD_DataCollectionProcess_Q30_2
      ,CAST([PD_DataCollectionProcess_Q30_3]  AS INT) AS PD_DataCollectionProcess_Q30_3
      ,CAST([PD_DataCollectionProcess_Q30_4]  AS INT) AS PD_DataCollectionProcess_Q30_4
      ,CAST([PD_DataCollectionProcess_Q30_5]  AS INT) AS PD_DataCollectionProcess_Q30_5
      ,CAST([PD_DataCollectionProcess_Q30_6]  AS INT) AS PD_DataCollectionProcess_Q30_6
      ,CAST([PD_DataCollectionProcess_Q30_7]  AS INT) AS PD_DataCollectionProcess_Q30_7
      ,CAST([PD_DataCollectionProcess_Q31_1]  AS INT) AS PD_DataCollectionProcess_Q31_1
      ,CAST([PD_DataCollectionProcess_Q31_2]  AS INT) AS PD_DataCollectionProcess_Q31_2
      ,CAST([PD_DataCollectionProcess_Q31_3]  AS INT) AS PD_DataCollectionProcess_Q31_3
      ,CAST([PD_DataCollectionProcess_Q31_4]  AS INT) AS PD_DataCollectionProcess_Q31_3
      ,CAST([PD_DataCollectionProcess_Q32_1]  AS INT) AS PD_DataCollectionProcess_Q32_1
      ,CAST([PD_DataCollectionProcess_Q32_2]  AS INT) AS PD_DataCollectionProcess_Q32_2
      ,CAST([PD_DataCollectionProcess_Q32_3]  AS INT) AS PD_DataCollectionProcess_Q32_3
      ,CAST([PD_DataCollectionProcess_Q32_4]  AS INT) AS PD_DataCollectionProcess_Q32_4
      ,CAST([PD_DataCollectionProcess_Q32_5]  AS INT) AS PD_DataCollectionProcess_Q32_5
      ,CAST([PD_DataCollectionProcess_Q32_6]  AS INT) AS PD_DataCollectionProcess_Q32_6
      ,CAST([PD_DataCollectionProcess_Q32_7]  AS INT) AS PD_DataCollectionProcess_Q32_7
      ,CAST([PD_DataCollectionProcess_Q33_1]  AS INT) AS PD_DataCollectionProcess_Q33_1
      ,CAST([PD_DataCollectionProcess_Q33_2]  AS INT) AS PD_DataCollectionProcess_Q33_2
      ,CAST([PD_DataCollectionProcess_Q33_3]  AS INT) AS PD_DataCollectionProcess_Q33_3
      ,CAST([PD_DataCollectionProcess_Q33_4]  AS INT) AS PD_DataCollectionProcess_Q33_4
      ,CAST([PD_DataCollectionProcess_Q34_1]  AS INT) AS PD_DataCollectionProcess_Q34_1
      ,CAST([PD_DataCollectionProcess_Q34_2]  AS INT) AS PD_DataCollectionProcess_Q34_2
      ,CAST([PD_DataCollectionProcess_Q34_3]  AS INT) AS PD_DataCollectionProcess_Q34_3
      ,CAST([PD_DataCollectionProcess_Q35_1]  AS INT) AS PD_DataCollectionProcess_Q35_1
      ,CAST([PD_DataCollectionProcess_Q35_2]  AS INT) AS PD_DataCollectionProcess_Q35_2
  FROM [ISBEPI_DEV].[dbo].[Program_Director_Survey] WHERE ([Schd_ID] = @Schd_ID)">
             <SelectParameters>
                 <asp:ControlParameter ControlID="hfSchdId" Name="Schd_ID" PropertyName="Value" Type="Int32" />
             </SelectParameters>
         </asp:SqlDataSource>
    </div>
    <div style="width: 100%; height: 400px; overflow: scroll">
        <h4 runat="server" id="h4" visible="false"> Question 12 to 18</h4>
        <asp:DataGrid ID="DataGrid2" runat="server"></asp:DataGrid>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ISBEPI_DEV %>" SelectCommand="SELECT [PD_EDUCATIONANDEXPERIENCE_Q12_1], [PD_EDUCATIONANDEXPERIENCE_Q12_2], [PD_EDUCATIONANDEXPERIENCE_Q12_3], [PD_EDUCATION_Q13], [PD_EDUCATION_Q14], [PD_EDUCATION_Q15], [PD_EDUCATION_Q16], [PD_EDUCATION_Q17], [PD_EDUCATION_Q18] FROM [Program_Director_Survey_Q12toQ16_Education_And_Experience] WHERE ([Schd_ID] = @Schd_ID)">
            <SelectParameters>
                <asp:ControlParameter ControlID="hfSchdId" Name="Schd_ID" PropertyName="Value" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
    </div>
    <asp:Button ID="btnExcel" runat="server" Text="Export To Excel" OnClick="btnExcel_Click" Visible="False" />
         </div>
</asp:Content>
